# Generated by Django 5.1.6 on 2025-02-28 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('location', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('salary_range', models.CharField(max_length=50)),
                ('employmentType', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('C', 'Contract'), ('F', 'Freelance'), ('I', 'Intern')], default='FT', max_length=2)),
                ('experienceLevel', models.CharField(choices=[('E', 'Entry Level'), ('M', 'Mid Level'), ('S', 'Senior Level')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField()),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
    ]
