# Generated by Django 5.1.6 on 2025-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(max_length=1000),
        ),
    ]
